# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 06307aadd1d7c20e3a03fa796696d6e5cac8874ce160377d2bd65cb23cccf1be23260ef8d40079cb5b27dea6474edeb3457566fd3417d43b0f4b797cd61420ce

test:
  secret_key_base: 4397507d4c1725d78a696f9d723e2b8822d827bbc1a978e81b52431ad682f3a3f032ac37fa369a828aa729748421c4fbb5279cd84acec0552221fdee9b990405

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
